# Generated by Django 6.0.6 on 2026-06-08 12:47

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to='resumes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('raw_text', models.TextField(blank=True, help_text='Plain text extracted from the uploaded PDF by pypdf.')),
                ('structured_data', models.JSONField(blank=True, default=dict, help_text='Structured résumé data extracted by Gemini.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Failure detail captured when status is FAILED.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='resumes_res_status_dd2fd3_idx'), models.Index(fields=['-created_at'], name='resumes_res_created_faa43b_idx')],
            },
        ),
    ]
