# Generated by Django 6.0.6 on 2026-06-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='tailored_data',
            field=models.JSONField(blank=True, default=dict, help_text='Resume structured data rewritten toward this job.'),
        ),
    ]
